language: cpp
sudo: required
os: linux
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons:
  apt:
    packages:
      - python3-pip

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.15/cmake-3.15.0-Linux-x86_64.sh
  - chmod +x cmake-3.15.0-Linux-x86_64.sh
  - ./cmake-3.15.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y python3
  - pip install --upgrade pip
  - pip install conan
  - conan user
 
  # (fake) install dependencies (usually involves wget, configure, make, ...)
# install into cache folder (build binaries+headers only, no sources and do NOT build there)
# - mkdir -p $HOME/.cache
# - touch $HOME/.cache/mydependency.so

script:
    - conan create . user/channel
    - chmod +x build.sh 
    - ./build.sh
