language: python
python: "3.7"
dist: "xenial"
sudo: required
os: linux
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.15/cmake-3.15.0-Linux-x86_64.sh
  - chmod +x cmake-3.15.0-Linux-x86_64.sh
  - ./cmake-3.15.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  - pip install conan
  - conan user
 
  # (fake) install dependencies (usually involves wget, configure, make, ...)
# install into cache folder (build binaries+headers only, no sources and do NOT build there)
# - mkdir -p $HOME/.cache
# - touch $HOME/.cache/mydependency.so

script:
    - cd build && conan install .. --build=missing
    - chmod +x build.sh 
    - ./build.sh
